### PR TITLE
Rename package

### PR DESCRIPTION
**Pull request by aalmiray**
Fix for #156

---
This change is [Reviewable](https://reviewable.io/reviews/jdeferred/jdeferred/157)

### CODE REVIEW

**Comment by sclassen** [comment]
Reviewed 197 of 198 files at r1.
Review status: 103 of 104 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.gradle, line 25 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/157#-L0WbMNcnFxZUS4_K4Yd:-L0WbMNdICOBh8zFggAq:b-pnnwt8) ([raw file](https://github.com/jdeferred/jdeferred/blob/090d1da54ff048114c2822bd6c2d3f5679462d14/build.gradle#L25)):*
> ```Gradle
> 
>     dependencies {
>         classpath 'org.kt3k.gradle.plugin:coveralls-gradle-plugin:2.8.2'
> ```

Do you want to split the dependencies update into a separate PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/157)*

**Comment by aalmiray** [comment]
Review status: 103 of 104 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.gradle, line 25 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/157#-L0WbMNcnFxZUS4_K4Yd:-L0WdgIRtvt28RsdD3V-:b9ex3iu) ([raw file](https://github.com/jdeferred/jdeferred/blob/090d1da54ff048114c2822bd6c2d3f5679462d14/build.gradle#L25)):*
<details><summary><i>Previously, sclassen wrote…</i></summary><blockquote>

Do you want to split the dependencies update into a separate PR?
</blockquote></details>

they are small. Should not affect any other commits anyway

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/157)*

**Comment by sclassen** [comment]
Reviewed 1 of 198 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/157)*

**Comment by sclassen** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/157#-:-L0We5OaWWlxgArXjU4E:bnfp4nl)*

**Comment by saturnism** [comment]
:lgtm:

---

Reviewed 198 of 198 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/157#-:-L0YDXlPhUgAYPXaXqNF:bnfp4nl)*

**Comment by aalmiray** [comment]
rebased PR with latest sources from `2.x`

**Comment by saturnism** [comment]
:lgtm:

---

Review status: 96 of 104 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/157#-:-L1W0ZuQ0ySKBgpAwtvH:bnfp4nl)*

**Comment by saturnism** [comment]
Reviewed 8 of 198 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/157)*

**Comment by saturnism** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/157#-:-L1W1WJ1c4C5pUKz-48r:bnfp4nl)*

**Comment by saturnism** [comment]
hm.. i thought i was able to fix the README.md conflict from the web editor

**Comment by saturnism** [comment]
there we go...

**Review by Andyadame — COMMENTED** [review]
173403a24f42e8e00edc25c80cd93c3b3e98c8a3

**Pull request merged**
