### PR TITLE
2.x Ability to take Iterable based on #104

### PR DESCRIPTION
**Pull request by saturnism**
For #115 #104 /cc @SimY4

---
This change is [Reviewable](https://reviewable.io/reviews/jdeferred/jdeferred/121)

### CODE REVIEW

**Comment by aalmiray** [comment]
I thought the change was to be added to the `2.x` branch instead of `master`.

**Comment by aalmiray** [comment]
Also, this PR includes all changes form #120. I think we need to merge #120 into `2.x` before any other PRs can target that branch.

**Comment by saturnism** [comment]
oops, needed to update the base branch 2.x :)

**Comment by saturnism** [comment]
quick ping - this should be based properly w/ the branch

**Comment by aalmiray** [comment]
Reviewed 2 of 40 files at r1, 5 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[subprojects/jdeferred-android/src/main/java/org/jdeferred/impl/DefaultAndroidDeferredManager.java, line 391 at r3](https://reviewable.io:443/reviews/jdeferred/jdeferred/121#-KwonPwVbjKCg2FDjC7C:-KwonPwVbjKCg2FDjC7D:bbd3rxh) ([raw file](https://github.com/jdeferred/jdeferred/blob/b6749040fdb7ef1654817158853e6c3c6912f238/subprojects/jdeferred-android/src/main/java/org/jdeferred/impl/DefaultAndroidDeferredManager.java#L391)):*
> ```Java
> 
> 	@Override
> 	protected Promise toPromise(Object o) {
> ```

`Promise<?, ?, ?>`

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredManager.java, line 378 at r3](https://reviewable.io:443/reviews/jdeferred/jdeferred/121#-KwonFj0WoqJaODwoZO3:-KwonFj1QdDhEHwtRVPB:bfr8o1g) ([raw file](https://github.com/jdeferred/jdeferred/blob/b6749040fdb7ef1654817158853e6c3c6912f238/subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredManager.java#L378)):*
> ```Java
> 	 * @return
> 	 */
> 	Promise<MultipleResults, OneReject<?>, MasterProgress> when(Iterable iterable);
> ```

`Iterable<?>` perhaps?

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/AbstractDeferredManager.java, line 19 at r3](https://reviewable.io:443/reviews/jdeferred/jdeferred/121#-KwonW3iKPpyNwGaRrSf:-KwonW3iKPpyNwGaRrSg:bowpulh) ([raw file](https://github.com/jdeferred/jdeferred/blob/b6749040fdb7ef1654817158853e6c3c6912f238/subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/AbstractDeferredManager.java#L19)):*
> ```Java
> 
> import org.jdeferred.*;
> import org.jdeferred.multiple.*;
> ```

star imports

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/AbstractDeferredManager.java, line 572 at r3](https://reviewable.io:443/reviews/jdeferred/jdeferred/121#-Kwoo4AjN8_p-oHJiu79:-Kwoo4AkBBGNTq07oklt:b-8kuc1r) ([raw file](https://github.com/jdeferred/jdeferred/blob/b6749040fdb7ef1654817158853e6c3c6912f238/subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/AbstractDeferredManager.java#L572)):*
> ```Java
> 			return (Promise) o;
> 		} else {
> 			DeferredObject deferred = new DeferredObject();
> ```

disallow this case for the time being. throw IAE

---

*[subprojects/jdeferred-core/src/test/java/org/jdeferred/impl/MultiplePromisesTest.java, line 31 at r3](https://reviewable.io:443/reviews/jdeferred/jdeferred/121#-KwooGsH7AAmST0tOCFG:-KwooGsH7AAmST0tOCFH:bowpulh) ([raw file](https://github.com/jdeferred/jdeferred/blob/b6749040fdb7ef1654817158853e6c3c6912f238/subprojects/jdeferred-core/src/test/java/org/jdeferred/impl/MultiplePromisesTest.java#L31)):*
> ```Java
> import org.junit.Test;
> 
> import java.util.*;
> ```

star imports

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/121)*

**Comment by saturnism** [comment]
@aalmiray i should've removed the star imports, and added parameterized types.  However, still not throwing IAE upon unrecognized types in iterable item.  Thinking out loud - if a person passes in a list of items, like [Runnable, Callable, String], the first 2 would've been submitted to execute, but the caller would've received an IAE w/o being able to get the promise back.  I.e., the work is submitted & executed, but the caller won't be able to get its result.

If we really want to throw IAE, then we need to do two passes - first pass making sure it's something we can convert, throw IAE if it isn't, then a second pass to do the actual conversion.  This also means subclasses will need implement the behavior properly.

**Comment by aalmiray** [comment]
Agreed. The two-pass behavior is the one we need. It must be specified in the Javadoc as a guideline for implementors

**Comment by aalmiray** [comment]
Reviewed 4 of 6 files at r6.
Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredManager.java, line 378 at r3](https://reviewable.io:443/reviews/jdeferred/jdeferred/121#-KwonFj0WoqJaODwoZO3:-KxGKEYbzkzCqKiJnEP5:b-oac5ya) ([raw file](https://github.com/jdeferred/jdeferred/blob/b6749040fdb7ef1654817158853e6c3c6912f238/subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredManager.java#L378)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

`Iterable<?>` perhaps?
</blockquote></details>

Javadoc refers to IllegalAccessException but it should be IllegalArgumentException

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/AbstractDeferredManager.java, line 572 at r3](https://reviewable.io:443/reviews/jdeferred/jdeferred/121#-Kwoo4AjN8_p-oHJiu79:-KxGKXS0Jw1PzfjnligL:b-6a77zc) ([raw file](https://github.com/jdeferred/jdeferred/blob/b6749040fdb7ef1654817158853e6c3c6912f238/subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/AbstractDeferredManager.java#L572)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

disallow this case for the time being. throw IAE
</blockquote></details>

impl throws both IAE and ISE but only IAE is mentioned in the javadoc. i think it’s enough to just throw IAE in this case

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/121)*

**Comment by saturnism** [comment]
Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredManager.java, line 378 at r3](https://reviewable.io:443/reviews/jdeferred/jdeferred/121#-KwonFj0WoqJaODwoZO3:-KxGOSeUNx7yhubcWvz2:blzo3v4) ([raw file](https://github.com/jdeferred/jdeferred/blob/b6749040fdb7ef1654817158853e6c3c6912f238/subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredManager.java#L378)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

Javadoc refers to IllegalAccessException but it should be IllegalArgumentException
</blockquote></details>

oops, wrong auto completion ;)

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/AbstractDeferredManager.java, line 572 at r3](https://reviewable.io:443/reviews/jdeferred/jdeferred/121#-Kwoo4AjN8_p-oHJiu79:-KxGOnYgEUZHV3d7seEi:bnnvhia) ([raw file](https://github.com/jdeferred/jdeferred/blob/b6749040fdb7ef1654817158853e6c3c6912f238/subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/AbstractDeferredManager.java#L572)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

impl throws both IAE and ISE but only IAE is mentioned in the javadoc. i think it’s enough to just throw IAE in this case
</blockquote></details>

there is a difference though - we should've never be in this state and would need to differentiate between whether something may have been submitted or not. this would be a true unexpected exception and should only occur if subclasses didn't implement proper behavior.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/121)*

**Comment by saturnism** [comment]
Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[subprojects/jdeferred-android/src/main/java/org/jdeferred/impl/DefaultAndroidDeferredManager.java, line 391 at r3](https://reviewable.io:443/reviews/jdeferred/jdeferred/121#-KwonPwVbjKCg2FDjC7C:-KxGPB7Hehj-SxpUtbeW:b-896fix) ([raw file](https://github.com/jdeferred/jdeferred/blob/b6749040fdb7ef1654817158853e6c3c6912f238/subprojects/jdeferred-android/src/main/java/org/jdeferred/impl/DefaultAndroidDeferredManager.java#L391)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

`Promise<?, ?, ?>`
</blockquote></details>

Done.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/AbstractDeferredManager.java, line 19 at r3](https://reviewable.io:443/reviews/jdeferred/jdeferred/121#-KwonW3iKPpyNwGaRrSf:-KxGPDzxTO17BxSM8j_8:b-896fix) ([raw file](https://github.com/jdeferred/jdeferred/blob/b6749040fdb7ef1654817158853e6c3c6912f238/subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/AbstractDeferredManager.java#L19)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

star imports
</blockquote></details>

Done.

---

*[subprojects/jdeferred-core/src/test/java/org/jdeferred/impl/MultiplePromisesTest.java, line 31 at r3](https://reviewable.io:443/reviews/jdeferred/jdeferred/121#-KwooGsH7AAmST0tOCFG:-KxGPFSAVhbbA3se5mgB:b-896fix) ([raw file](https://github.com/jdeferred/jdeferred/blob/b6749040fdb7ef1654817158853e6c3c6912f238/subprojects/jdeferred-core/src/test/java/org/jdeferred/impl/MultiplePromisesTest.java#L31)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

star imports
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/121)*

**Pull request merged**
