### PR TITLE
improve javadoc for the Pipe interfaces

### PR DESCRIPTION
**Pull request by sclassen**
part of #148

---
This change is [Reviewable](https://reviewable.io/reviews/jdeferred/jdeferred/150)

### CODE REVIEW

**Comment by aalmiray** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/150)*

**Comment by saturnism** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/150#-:-L-EVVw42r2QlEYXRclS:bnfp4nl)*

**Comment by saturnism** [comment]
ping @aalmiray, reviewable says there is 1 file to review :)

**Comment by aalmiray** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/150)*

**Pull request merged**
