### PR TITLE
add AlwaysPipe

### LINKED ISSUE #153: Is there a need for an AlwaysPipe?
Similar to the AlwaysCallback this would allow to pipe both resolve and rejection in a single implementation.

I would propose the following API:

    public interface AlwaysCallback<D, F, D_OUT, F_OUT, P_OUT> {
        Promise<D_OUT, F_OUT, P_OUT> pipeAlways(final State state, final D resolved, final F rejected);
    }

I see that this is only a convenience method as the same behaviour can be achieved with a DonePipe and a FailPipe.

### PR DESCRIPTION
**Pull request by sclassen**
resolves #153

---
This change is [Reviewable](https://reviewable.io/reviews/jdeferred/jdeferred/155)

### CODE REVIEW

**Comment by aalmiray** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/AlwaysPipe.java, line 30 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/155#-L072djQYRyrRxt5XfpA:-L072djQYRyrRxt5XfpB:b-ij96qb) ([raw file](https://github.com/jdeferred/jdeferred/blob/0e61afd0b4570c4ba2069455ea854252d64f1e33/subprojects/jdeferred-core/src/main/java/org/jdeferred/AlwaysPipe.java#L30)):*
> ```Java
>  * @param <D_OUT> Type of the output from this pipe
>  * @param <F_OUT> Type of the failure output from this pipe
>  * @param <P_OUT> Type of the progress output from this pipe
> ```

`P_OUT` could be `P` as it remains unchanged. Only `D` and `F` might be changed by the callback.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/155)*

**Comment by sclassen** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/AlwaysPipe.java, line 30 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/155#-L072djQYRyrRxt5XfpA:-L073GoQWzfegLkPyY8p:bde8e) ([raw file](https://github.com/jdeferred/jdeferred/blob/0e61afd0b4570c4ba2069455ea854252d64f1e33/subprojects/jdeferred-core/src/main/java/org/jdeferred/AlwaysPipe.java#L30)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

`P_OUT` could be `P` as it remains unchanged. Only `D` and `F` might be changed by the callback.
</blockquote></details>

Its a pure naming thing here. The correlation between P and P_OUT is done in the method on the Promise interface.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/155)*

**Comment by sclassen** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/AlwaysPipe.java, line 30 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/155#-L072djQYRyrRxt5XfpA:-L073q2wRqDBzHpzsmoV:b-uj8xcm) ([raw file](https://github.com/jdeferred/jdeferred/blob/0e61afd0b4570c4ba2069455ea854252d64f1e33/subprojects/jdeferred-core/src/main/java/org/jdeferred/AlwaysPipe.java#L30)):*
<details><summary><i>Previously, sclassen wrote…</i></summary><blockquote>

Its a pure naming thing here. The correlation between P and P_OUT is done in the method on the Promise interface.
</blockquote></details>

Regarding P_OUT see also #154 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/155)*

**Comment by aalmiray** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/AlwaysPipe.java, line 30 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/155#-L072djQYRyrRxt5XfpA:-L074KlAeNouJ2DfueUM:b-lv9fmz) ([raw file](https://github.com/jdeferred/jdeferred/blob/0e61afd0b4570c4ba2069455ea854252d64f1e33/subprojects/jdeferred-core/src/main/java/org/jdeferred/AlwaysPipe.java#L30)):*
<details><summary><i>Previously, sclassen wrote…</i></summary><blockquote>

Regarding P_OUT see also #154 
</blockquote></details>

Right, that's why I thought keeping the generic types simpler would be good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/155)*

**Comment by sclassen** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/AlwaysPipe.java, line 30 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/155#-L072djQYRyrRxt5XfpA:-L075fOKB3nJyo7ZMuz8:brdix3l) ([raw file](https://github.com/jdeferred/jdeferred/blob/0e61afd0b4570c4ba2069455ea854252d64f1e33/subprojects/jdeferred-core/src/main/java/org/jdeferred/AlwaysPipe.java#L30)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

Right, that's why I thought keeping the generic types simpler would be good
</blockquote></details>

So should I rename the generic parameter? I have no preference on the name. 
P_OUT follows the naming in the other pipes
P is more expressive

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/155)*

**Comment by aalmiray** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/AlwaysPipe.java, line 30 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/155#-L072djQYRyrRxt5XfpA:-L07GJgfTtb36KrPb_0x:bj5faf5) ([raw file](https://github.com/jdeferred/jdeferred/blob/0e61afd0b4570c4ba2069455ea854252d64f1e33/subprojects/jdeferred-core/src/main/java/org/jdeferred/AlwaysPipe.java#L30)):*
<details><summary><i>Previously, sclassen wrote…</i></summary><blockquote>

So should I rename the generic parameter? I have no preference on the name. 
P_OUT follows the naming in the other pipes
P is more expressive
</blockquote></details>

Yes, please rename to `P`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/155)*

**Comment by sclassen** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/AlwaysPipe.java, line 30 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/155#-L072djQYRyrRxt5XfpA:-L093bxbMBZGSQQJ-570:b-896fix) ([raw file](https://github.com/jdeferred/jdeferred/blob/0e61afd0b4570c4ba2069455ea854252d64f1e33/subprojects/jdeferred-core/src/main/java/org/jdeferred/AlwaysPipe.java#L30)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

Yes, please rename to `P`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/155)*

**Comment by saturnism** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/155#-:-L0TKOFyKOqmpn4qghbf:bnfp4nl)*

**Comment by saturnism** [comment]
quick ping @aalmiray - do you feel this is ready to be merged in?
i'd love to cut a 2.0 branch sometimes next week :D

**Comment by aalmiray** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/155#-:-L0UwRaemNE-oBi0HdJ6:bnfp4nl)*

**Pull request merged**
