### PR TITLE
Global Exception Handler

### PR DESCRIPTION
**Pull request by saturnism**
This change is [Reviewable](https://reviewable.io/reviews/jdeferred/jdeferred/131)

### CODE REVIEW

**Comment by aalmiray** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/DefaultExceptionHandler.java, line 32 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/131#-KxJAlc-j9AMVz8aFLkw:-KxJAlc166libHHsRAG5:b9hqdn8) ([raw file](https://github.com/jdeferred/jdeferred/blob/281d41b9f9cfe7751af6e43606a9c374a30b37a2/subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/DefaultExceptionHandler.java#L32)):*
> ```Java
>     @Override
>     public void handleException(CallbackType callbackType, Exception e) {
>         LOG.error("An uncaught exception occured in " + callbackType, e);
> ```

s/occured/ocurred/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/131)*

**Comment by saturnism** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/DefaultExceptionHandler.java, line 32 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/131#-KxJAlc-j9AMVz8aFLkw:-KxLMRdPHMX4nSWtGMSm:b-896fix) ([raw file](https://github.com/jdeferred/jdeferred/blob/281d41b9f9cfe7751af6e43606a9c374a30b37a2/subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/DefaultExceptionHandler.java#L32)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

s/occured/ocurred/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/131)*

**Comment by saturnism** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/DefaultExceptionHandler.java, line 32 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/131#-KxJAlc-j9AMVz8aFLkw:-KxLOW7CHpVPeq6hrK9I:b-896fix) ([raw file](https://github.com/jdeferred/jdeferred/blob/281d41b9f9cfe7751af6e43606a9c374a30b37a2/subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/DefaultExceptionHandler.java#L32)):*
<details><summary><i>Previously, saturnism (Ray Tsang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/131)*

**Comment by saturnism** [comment]
@aalmiray btw, I renamed the callback handler to be a bit more explicit in case we need to add additional handlers in the future.

**Comment by aalmiray** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/131#-:-KxOxhviTUHDb2Qh5jMO:bnfp4nl)*

**Pull request merged**
