### PR TITLE
Cancellation handler

### PR DESCRIPTION
**Pull request by aalmiray**
As discussed during BaselOne, `DeferredFutureTask` is now able to cleanup any resources when the underlying task is interrupted or cancelled.
Tests were parameterized with JUnitParams,

---
This change is [Reviewable](https://reviewable.io/reviews/jdeferred/jdeferred/126)

### CODE REVIEW

**Comment by saturnism** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredFutureTask.java, line 166 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/126#-KwuPUmYtgnTtZwJOWdK:-KwuPUmYtgnTtZwJOWdL:b-e1u5te) ([raw file](https://github.com/jdeferred/jdeferred/blob/d798fa9408365ba9d25a5ece3c389fce19825d3f/subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredFutureTask.java#L166)):*
> ```Java
> 		} catch (InterruptedException e) {
> 			// TODO: should cleanup be called here?
> 			cleanup();
> ```

this is a tough one.. what should be the right behavior? 
should pass the cancelation cause (the exception) into the cancellation handler?

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredFutureTask.java, line 175 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/126#-KwuPDkdkTew4r7MGcoz:-KwuPDkdkTew4r7MGcp-:bexkeq8) ([raw file](https://github.com/jdeferred/jdeferred/blob/d798fa9408365ba9d25a5ece3c389fce19825d3f/subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredFutureTask.java#L175)):*
> ```Java
> 		} catch (Throwable t) {
> 			// TODO: this exception will be lost. Handle it via global ExceptionHandler?
> 			t.printStackTrace();
> ```

should log the error here. let's add a TODO to forward to global handling when we have it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/126)*

**Comment by aalmiray** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredFutureTask.java, line 166 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/126#-KwuPUmYtgnTtZwJOWdK:-Kwv7PwHvN3-xdbsK7jP:b-yp4p6i) ([raw file](https://github.com/jdeferred/jdeferred/blob/d798fa9408365ba9d25a5ece3c389fce19825d3f/subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredFutureTask.java#L166)):*
<details><summary><i>Previously, saturnism (Ray Tsang) wrote…</i></summary><blockquote>

this is a tough one.. what should be the right behavior? 
should pass the cancelation cause (the exception) into the cancellation handler?
</blockquote></details>

Indeed. Decided to pass the exception/cause as this case is triggered when the executing thread is interrupted from the outside the task

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredFutureTask.java, line 175 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/126#-KwuPDkdkTew4r7MGcoz:-Kwv7_CZ0lDeje3V4n8v:b-7rl0jd) ([raw file](https://github.com/jdeferred/jdeferred/blob/d798fa9408365ba9d25a5ece3c389fce19825d3f/subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredFutureTask.java#L175)):*
<details><summary><i>Previously, saturnism (Ray Tsang) wrote…</i></summary><blockquote>

should log the error here. let's add a TODO to forward to global handling when we have it.
</blockquote></details>

done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/126)*

**Comment by saturnism** [comment]
Reviewed 1 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredFutureTask.java, line 175 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/126#-KwuPDkdkTew4r7MGcoz:-KxA7OSVMYlkM3rhgdEl:by2anx7) ([raw file](https://github.com/jdeferred/jdeferred/blob/d798fa9408365ba9d25a5ece3c389fce19825d3f/subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredFutureTask.java#L175)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

done.
</blockquote></details>

still see `t.printStackTrace()`. That should be removed now that we have the log entry, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/126)*

**Comment by aalmiray** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredFutureTask.java, line 175 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/126#-KwuPDkdkTew4r7MGcoz:-KxD7U92UfWy46nXUCFF:b-7ql1td) ([raw file](https://github.com/jdeferred/jdeferred/blob/d798fa9408365ba9d25a5ece3c389fce19825d3f/subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredFutureTask.java#L175)):*
<details><summary><i>Previously, saturnism (Ray Tsang) wrote…</i></summary><blockquote>

still see `t.printStackTrace()`. That should be removed now that we have the log entry, right?
</blockquote></details>

fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/126)*

**Comment by saturnism** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/126#-:-KxDsCkNNrVul2NZeFMU:bnfp4nl)*

**Pull request merged**
