### PR TITLE
improve javadoc and fix some warnings for Promise interface

### PR DESCRIPTION
**Pull request by sclassen**
part of #148

---
This change is [Reviewable](https://reviewable.io/reviews/jdeferred/jdeferred/149)

### CODE REVIEW

**Comment by aalmiray** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java, line 82 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/149#-KzzhRFYCfo2fkmP2g3V:-KzzhRFZgZedz7uGeouD:b-nqyxrc) ([raw file](https://github.com/jdeferred/jdeferred/blob/bbd106ae85916e292e88138aa9ba50f89a996877/subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java#L82)):*
> ```Java
> 	/**
> 	 * @see State#PENDING
> 	 * @return
> ```

boolean getters are quite dull and repetitive yet these methods are state queries

    /**
     * Queries the state of this promise, return {@code true} if its {@code State.PENDING}.
     * @see State#PENDING
     * @return {@code true} if the current state of this promise is {@code State.PENDING}, {@code false} otherwise.
     */

In other words, we must find a pattern that describe these methods, then apply it to all of them :-)

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java, line 192 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/149#-KzzhCke1Ni5ri4Cw1oi:-KzzhCke1Ni5ri4Cw1oj:b-kl8g4c) ([raw file](https://github.com/jdeferred/jdeferred/blob/d766bab9d1daa5339aba8692733e071c5b258afc/subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java#L192)):*
> ```Java
> 	 * <code>
> 	 * promise.then(new DonePipe<Integer, Integer, String, Void>() {
> 	 *   {@literal @}Override
> ```

good catch!

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java, line 220 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/149#-KzzhEquA3hTCwdpm63l:-KzzhEquA3hTCwdpm63m:b-1a9vpk) ([raw file](https://github.com/jdeferred/jdeferred/blob/bbd106ae85916e292e88138aa9ba50f89a996877/subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java#L220)):*
> ```Java
> 	 * 
> 	 * @param donePipe
> 	 * @param failPipe
> ```

I think it's best to keep the `@param` tags and add some text to them.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java, line 321 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/149#-KzzgQOf1i1hqNuAAGOO:-KzzgQOf1i1hqNuAAGOP:b9f8yd8) ([raw file](https://github.com/jdeferred/jdeferred/blob/bbd106ae85916e292e88138aa9ba50f89a996877/subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java#L321)):*
> ```Java
> 	 * @see Deferred#notify(Object)
> 	 * @param callback
> 	 * @return
> ```

I think it would be better to keep the return tag and add some text to it. The obvious thing is to say the method returns a `Promise` but with a certain state that reflects the method's input (in this case, a callback that can handle progress notifications). However there's a bigger issue in most of these methods, the returned `Promise` is the same instance (with the current impl). Why is important to remark this? People coming from RxJava/Reactor might expect a new instance as `Observable`/`Flux` decorate instead the receiver instead of mutating its internal state. WDYT @saturnism ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/149)*

**Comment by sclassen** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java, line 82 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/149#-KzzhRFYCfo2fkmP2g3V:-L-Je81CT2JuCd-eK4GS:b-896fix) ([raw file](https://github.com/jdeferred/jdeferred/blob/bbd106ae85916e292e88138aa9ba50f89a996877/subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java#L82)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

boolean getters are quite dull and repetitive yet these methods are state queries

    /**
     * Queries the state of this promise, return {@code true} if its {@code State.PENDING}.
     * @see State#PENDING
     * @return {@code true} if the current state of this promise is {@code State.PENDING}, {@code false} otherwise.
     */

In other words, we must find a pattern that describe these methods, then apply it to all of them :-)
</blockquote></details>

Done.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java, line 192 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/149#-KzzhCke1Ni5ri4Cw1oi:-L-JeMYvmHIjvn8qBtd-:bd5l6n4) ([raw file](https://github.com/jdeferred/jdeferred/blob/d766bab9d1daa5339aba8692733e071c5b258afc/subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java#L192)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

good catch!
</blockquote></details>

thanks.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java, line 220 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/149#-KzzhEquA3hTCwdpm63l:-L-JeQhIywB1mC463QaT:b-896fix) ([raw file](https://github.com/jdeferred/jdeferred/blob/bbd106ae85916e292e88138aa9ba50f89a996877/subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java#L220)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

I think it's best to keep the `@param` tags and add some text to them.
</blockquote></details>

Done.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java, line 321 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/149#-KzzgQOf1i1hqNuAAGOO:-L-JeVhdCINQw7ByBKy-:bv0izga) ([raw file](https://github.com/jdeferred/jdeferred/blob/bbd106ae85916e292e88138aa9ba50f89a996877/subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java#L321)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

I think it would be better to keep the return tag and add some text to it. The obvious thing is to say the method returns a `Promise` but with a certain state that reflects the method's input (in this case, a callback that can handle progress notifications). However there's a bigger issue in most of these methods, the returned `Promise` is the same instance (with the current impl). Why is important to remark this? People coming from RxJava/Reactor might expect a new instance as `Observable`/`Flux` decorate instead the receiver instead of mutating its internal state. WDYT @saturnism ?
</blockquote></details>

Done.
I added @result to all methods which are non void and state whether a new object or "this" is returned

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/149)*

**Comment by sclassen** [comment]
anybody an idea how coverage can decrease if only javadoc on an interface is changed??

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/149#-:-L-JgKItACnFB8nCxD3r:b-pnr0t3)*

**Comment by aalmiray** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/149)*

**Pull request merged**
