### PR TITLE
improve javadoc for the Callback interfaces

### PR DESCRIPTION
**Pull request by sclassen**
part of #148

---
This change is [Reviewable](https://reviewable.io/reviews/jdeferred/jdeferred/152)

### CODE REVIEW

**Comment by aalmiray** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/ProgressCallback.java, line 20 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/152#-Kzzmb_2mDVOvn5QtaZI:-Kzzmb_2mDVOvn5QtaZJ:b-n12f3d) ([raw file](https://github.com/jdeferred/jdeferred/blob/b9f9da52d0ab33f0308fd2993002b378a0c12fc0/subprojects/jdeferred-core/src/main/java/org/jdeferred/ProgressCallback.java#L20)):*
> ```Java
> /**
>  * A callback invoked when the {@code Promise} publishes intermediate results while it is still in the state
>  * {@link Promise.State#PENDING}.
> ```

may I suggest to rephrase as "while its state is still {@link Promise.State#PENDING}" ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/152)*

**Comment by aalmiray** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/152)*

**Comment by sclassen** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/FailCallback.java, line 19 at r2](https://reviewable.io:443/reviews/jdeferred/jdeferred/152#-L-0bAu6K052Ax4b5_nZ:-L-0bAu6K052Ax4b5_n_:bz9lbfx) ([raw file](https://github.com/jdeferred/jdeferred/blob/13854f065f387b54c14d9af081919cdfb5b54807/subprojects/jdeferred-core/src/main/java/org/jdeferred/FailCallback.java#L19)):*
> ```Java
> 
> /**
>  * A callback invoked when the {@code Promise}'s state becomes {@link Promise.State#REJECTED}.
> ```

After sleeping one night over this, I am no longer sure if changing "is" to "becomes" is a good thing.
Becomes expresses the fact that the callback is invoked at the time of resolving. But it does not express that a callback is fired immediately when the promise is already resolved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/152)*

**Comment by saturnism** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/FailCallback.java, line 19 at r2](https://reviewable.io:443/reviews/jdeferred/jdeferred/152#-L-0bAu6K052Ax4b5_nZ:-L-EW-a6YBKo-lMr8B5w:bm6ed6g) ([raw file](https://github.com/jdeferred/jdeferred/blob/13854f065f387b54c14d9af081919cdfb5b54807/subprojects/jdeferred-core/src/main/java/org/jdeferred/FailCallback.java#L19)):*
<details><summary><i>Previously, sclassen wrote…</i></summary><blockquote>

After sleeping one night over this, I am no longer sure if changing "is" to "becomes" is a good thing.
Becomes expresses the fact that the callback is invoked at the time of resolving. But it does not express that a callback is fired immediately when the promise is already resolved.
</blockquote></details>

Hmm, perhaps it'll be more clear to state both.   Looking at the JavaDoc for where this is actually used, I don't think it was clearly expressed there either :(

Now I think about it, the behavior should be documented in the Promise itself:

https://github.com/jdeferred/jdeferred/blob/master/subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java

While the JavaDoc for the callback can probably just refer to the Promise behaviors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/152)*

**Comment by sclassen** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/FailCallback.java, line 19 at r2](https://reviewable.io:443/reviews/jdeferred/jdeferred/152#-L-0bAu6K052Ax4b5_nZ:-L-EXvDhtZzaWLILpral:b-f0lakq) ([raw file](https://github.com/jdeferred/jdeferred/blob/13854f065f387b54c14d9af081919cdfb5b54807/subprojects/jdeferred-core/src/main/java/org/jdeferred/FailCallback.java#L19)):*
<details><summary><i>Previously, saturnism (Ray Tsang) wrote…</i></summary><blockquote>

Hmm, perhaps it'll be more clear to state both.   Looking at the JavaDoc for where this is actually used, I don't think it was clearly expressed there either :(

Now I think about it, the behavior should be documented in the Promise itself:

https://github.com/jdeferred/jdeferred/blob/master/subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java

While the JavaDoc for the callback can probably just refer to the Promise behaviors.


</blockquote></details>

OK, I will incorporate this into the pull request #149 for promise interface. I also think you are right, it is best documented at the location where the interface is used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/152)*

**Comment by sclassen** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[subprojects/jdeferred-core/src/main/java/org/jdeferred/ProgressCallback.java, line 20 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/152#-Kzzmb_2mDVOvn5QtaZI:-L-EYQFlsPqU9RA5Qt3i:bb7f2mf) ([raw file](https://github.com/jdeferred/jdeferred/blob/b9f9da52d0ab33f0308fd2993002b378a0c12fc0/subprojects/jdeferred-core/src/main/java/org/jdeferred/ProgressCallback.java#L20)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

may I suggest to rephrase as "while its state is still {@link Promise.State#PENDING}" ?
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/152)*

**Comment by aalmiray** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/152)*

**Pull request merged**
