### PR TITLE
Adds the possibility to cancel all callbacks of a promise

### PR DESCRIPTION
**Pull request by raycoarana**
This method try to help apps developers that wan't to prevent leaks of Activity/Fragment when a user is leaving them and a promise is pending to be completed. Removing all callbacks let the Activity/Fragment to be garbage collected.

---
This change is [Reviewable](https://reviewable.io/reviews/jdeferred/jdeferred/50)

### CODE REVIEW

**Comment by saturnism** [comment]
hiya - which version of jdeferred are you using?  the latest should've been patched where finished promises would've cleared all the callbacks.

**Comment by raycoarana** [comment]
The case what I see we need this is when the Promise is not already finish
but the user want to leave the screen (the activity or fragment un
Android). If we don't clear the callbacks at that moment, the screen will
be leaked until the promise finishes.

**Comment by Wattos** [comment]
I would :+1: the request for a cancel() method on a promise. However, this changeset does not seem complete, as ideally the creator of a deferred object would be able to register on cancel and do something. As an example, consider having a promise for an API Http request. Ideally, you would like to be able to cancel the request as well.

**Comment by saturnism** [comment]
agreed - I do feel we can implement cancel if and only if the underlying task is also cancelable.  But, a promise is also immutable.  What do you feel about making Deferred object cancelable?

**Comment by lkho** [comment]
Hi everyone, how is this going on? I'm waiting for it to be merged :)
Maybe we can create a subclass for CancellableDeferred and CancellablePromise since the original meaning of deferred and promise do not contain a cancel mechanism.

**Comment by saturnism** [comment]
hi @raycoarana! just getting back to this, I'm thinking of renaming the method to something else. p.cancel() feels like we are canceling the promise/task, rather than cleaning up the handlers/callbacks.

Would you be able to suggest another name?

**Comment by raycoarana** [comment]
Sure, maybe clearCallbacks() is clear enough. What do you think?

**Comment by aalmiray** [comment]
it looks to me that the actual problem is that the task may still be running, not the fact that the promise has at least one callback registered. If this is the case then we must find a way to cancel tasks submitted via `dm.when()` when the first task rejects a value, similarly as it's done with `dm.race()`. Be aware that automatic cancellation of tasks can only happen when the submitted type is not a `Promise` but a `Runnable`/`Callable`/`DeferredRunnable`/`DeferredCallable`/`DeferredFutureTask`/`Future`/`DeferredAsyncTask`.

**Pull request closed without merging**
