### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by aalmiray**
This change is [Reviewable](https://reviewable.io/reviews/jdeferred/jdeferred/134)

### CODE REVIEW

**Comment by saturnism** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 269 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/134#-Kx_1VZvQfFCM3AxEQox:-Kx_1VZwh0RVgWhIMI2i:buz3bg1) ([raw file](https://github.com/jdeferred/jdeferred/blob/86a9fb235eb4d6888ba592848d75c377f84663db/README.md#L269)):*
> ```Markdown
> ```
> 
> <a name="example-race"></a>When
> ```

Let's mention "since" here as well. E..g, Pipe section

---

*[README.md, line 299 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/134#-Kx_1lvfMryE2_rLBcaq:-Kx_1lvfMryE2_rLBcar:buz3bg1) ([raw file](https://github.com/jdeferred/jdeferred/blob/86a9fb235eb4d6888ba592848d75c377f84663db/README.md#L299)):*
> ```Markdown
> Calls to `when` with multiple arguments (up to five) will produce results with typesafe getters.
> 
> <a name="example-when"></a>Race
> ```

Let's mention "since" here as well. E..g, Pipe section

---

*[README.md, line 343 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/134#-Kx_1nsKbqhuD62PL98I:-Kx_1nsKbqhuD62PL98J:b-zf1opl) ([raw file](https://github.com/jdeferred/jdeferred/blob/86a9fb235eb4d6888ba592848d75c377f84663db/README.md#L343)):*
> ```Markdown
> may define a task that implements the `org.jdeferred.CancellationHandler` interface or pass and extra argument to
> `DeferredFutureTask` with such implementation, for example
> ```

we should also have an example w/ DeferredFutureTask to attach a handler in case it cannot be added to a Runnable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/134)*

**Comment by aalmiray** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 269 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/134#-Kx_1VZvQfFCM3AxEQox:-Kx_Bq5rpAq0FeuixXfB:bb7f2mf) ([raw file](https://github.com/jdeferred/jdeferred/blob/86a9fb235eb4d6888ba592848d75c377f84663db/README.md#L269)):*
<details><summary><i>Previously, saturnism (Ray Tsang) wrote…</i></summary><blockquote>

Let's mention "since" here as well. E..g, Pipe section
</blockquote></details>

done

---

*[README.md, line 299 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/134#-Kx_1lvfMryE2_rLBcaq:-Kx_Bqk-WgLJFZ4BjDKY:bb7f2mf) ([raw file](https://github.com/jdeferred/jdeferred/blob/86a9fb235eb4d6888ba592848d75c377f84663db/README.md#L299)):*
<details><summary><i>Previously, saturnism (Ray Tsang) wrote…</i></summary><blockquote>

Let's mention "since" here as well. E..g, Pipe section
</blockquote></details>

done

---

*[README.md, line 343 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/134#-Kx_1nsKbqhuD62PL98I:-Kx_Bs8Ryf9QQ4Nll03b:bb7f2mf) ([raw file](https://github.com/jdeferred/jdeferred/blob/86a9fb235eb4d6888ba592848d75c377f84663db/README.md#L343)):*
<details><summary><i>Previously, saturnism (Ray Tsang) wrote…</i></summary><blockquote>

we should also have an example w/ DeferredFutureTask to attach a handler in case it cannot be added to a Runnable.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/134)*

**Comment by saturnism** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 299 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/134#-Kx_1lvfMryE2_rLBcaq:-Kx_Z3bb7UKq39s1CKgc:b-9quzw) ([raw file](https://github.com/jdeferred/jdeferred/blob/86a9fb235eb4d6888ba592848d75c377f84663db/README.md#L299)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

done
</blockquote></details>

hmm, i don't think the change is pushed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/134)*

**Comment by aalmiray** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 299 at r1](https://reviewable.io:443/reviews/jdeferred/jdeferred/134#-Kx_1lvfMryE2_rLBcaq:-Kx_bSxc7uZ7UX_t6xWd:b-ld77ir) ([raw file](https://github.com/jdeferred/jdeferred/blob/86a9fb235eb4d6888ba592848d75c377f84663db/README.md#L299)):*
<details><summary><i>Previously, saturnism (Ray Tsang) wrote…</i></summary><blockquote>

hmm, i don't think the change is pushed.
</blockquote></details>

right. Just rebased and pushed again

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/134)*

**Comment by saturnism** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/134#-:-KxdNGJHoOsqExF2J5IN:bnfp4nl)*

**Comment by saturnism** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/134)*

**Pull request merged**
