### PR TITLE
simplify DeferredPromise by extending DelegatingPromise

### LINKED ISSUE #143: DeferredPromise can be simplified by extending DelegatingPromise
Almost all code from DeferredPromise can be deleted when the class extends DelegatingPromise.

There is a side effect to this change:
- DeferredPromise will inherit the protected method `Promise<D, F, P> getDelegate()` from DelegatingPromise. Currently the promise is private and therefore not accessible outside of the DeferredPromise.

### PR DESCRIPTION
**Pull request by sclassen**
fixes #143

---
This change is [Reviewable](https://reviewable.io/reviews/jdeferred/jdeferred/144)

### CODE REVIEW

**Comment by aalmiray** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/144#-:-KxoYQhVIxRdfhlwp-W6:bnfp4nl)*

**Comment by saturnism** [comment]
Is this suppose to go into 2.x branch?

**Comment by aalmiray** [comment]
Uh right, It makes more sense to target 2.x. @sclassen could you target `jdeferred:2.x` instead of `master`? thanx

**Comment by sclassen** [comment]
changed target branch to 2.x and rebased source branch

**Comment by aalmiray** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jdeferred/jdeferred/144)*

**Comment by saturnism** [comment]
thanks!

**Pull request merged**
